- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "iac-rds-instance.crcj7z22xflc.us-east-1.rds.amazonaws.com"
    login_user: "admin"
    login_password: "minda123"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "iac-rds-instance.crcj7z22xflc.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "admin" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "minda123" }
