---
- hosts: tag_Name_ACS_nginx
- name: nginx assignment
  import_playbook: ../static-assignments/nginx.yml

- hosts: tag_Name_ACS_tooling
- name: tooling assignment
  import_playbook: ../static-assignments/tooling.yml

- hosts: tag_Name_ACS_wordpress
- name: wordpress assignment
  import_playbook: ../static-assignments/wordpress.yml
